agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('login/', views.login_in, name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/create-cliente', views.create_cliente, name='create_cliente'),
    path('perfil/', views.perfil, name='perfil'),
    path('empresa/', views.empresa, name='empresa'),
    path('servico/', views.servico, name='servico'),
    path('agenda/', views.agenda, name='agenda'),
    path('agendamento/', views.agendamento, name='agendamento'),
    path('gerarAgendamento/', views.gerarAgendamento, name='gerarAgendamento'),
    path('gerar-agendamento-programado/', views.gerarAgendamentoProgramado, name='gerarAgendamentoProgramado'),
    path('cancelar-agendamento/', views.cancelarAgendamento, name='cancelarAgendamento'),
    path('cadastrar-servico/', views.cadastrarServico, name='cadastrarServico'),
    path('cadastrar-funcionario/', views.cadastrarFuncionario, name='cadastrarFuncionario'),
    path('update-funcionario/', views.updateFuncionario, name='updateFuncionario'),
    path('deletar-servico/', views.deletarServico, name='deletarServico'),
    path('deletar-empresa/', views.deletarEmpresa, name='deletarEmpresa'),
    path('deletar-funcionario/', views.deletarFuncionario, name='deletarFuncionario'),
]

servicoAgenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('agenda.urls'), name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):   
    TIPO_ADM_CHOICES = (('G', 'Gerente'), ('F', 'Funcionario'), ('C', 'Cliente'))
    
    id = models.AutoField(primary_key=True)
    celular = models.CharField(max_length=20, blank=True, null=True)
    username = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(unique=True)
    tipo = models.CharField(max_length=1, choices=TIPO_ADM_CHOICES)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    status = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']
    
class Dia(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=30)

class DiaSemanaFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    horaInicial = models.TimeField()
    horaFinal = models.TimeField()
    dia = models.ForeignKey(Dia, on_delete=models.SET_NULL, blank=True, null=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
class Cidade(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)

class Empresa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    logradouro = models.CharField(max_length=200, blank=True, null=True)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    descricao = models.CharField(max_length=200, blank=True, null=True)
    cep = models.CharField(max_length=200, blank=True, null=True)
    numero = models.CharField(max_length=200, blank=True, null=True)
    complemento = models.CharField(max_length=200, blank=True, null=True)
    status = models.BooleanField(default=True)
    gerente = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.SET_NULL, blank=True, null=True)
            
class Servico(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    descricao = models.CharField(max_length=200, blank=True, null=True)
    valor = models.FloatField()
    tempoServico = models.TimeField()
    intervalo = models.TimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.SET_NULL, blank=True, null=True)
    
class ServicoFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    servico = models.ForeignKey(Servico, on_delete=models.SET_NULL, blank=True, null=True)
    
        
class Agenda(models.Model):
    STATUS = (('M', 'Marcado'),('P', 'Programado'), ('E', 'Executado'), ('C', 'Cancelado'))
    id = models.AutoField(primary_key=True)
    create_data = models.DateTimeField(auto_now_add=True)
    data_inicio = models.DateTimeField()
    data_final = models.DateTimeField()
    status = models.CharField(max_length=1, choices=STATUS)
    servico = models.ForeignKey(Servico, on_delete=models.SET_NULL, blank=True, null=True)
    cliente = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='agendas_cliente')
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='agendas_funcionario')
    
class EmpresaFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.SET_NULL, blank=True, null=True)
    

agenda/views.py
from calendar import c
from cgi import print_arguments
from turtle import mode
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from agenda.util import encontrar_menor_maior_hora, dividir_horarios, filtrar_horarios_nao_ocupados
from agenda import models
from django.urls import resolve
from django.utils import timezone
from django.core.mail import send_mail



def index(request):
    return render(request, 'agenda/index.html')

def login_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)
                request.session['id_empresa'] = 11
                request.session['statusAgenda'] = 'M'
                if 'idCidade' in request.POST and request.POST['idCidade']:
                    request.session['id_cidade'] = request.POST['idCidade'] 

                if user.tipo == 'C':
                    return redirect('agenda:home')
                
                return redirect('agenda:perfil')
    else:
        form = AuthenticationForm()
        
    cidadesEmpresa = models.Empresa.objects.filter(gerente_id=3).values_list('cidade', flat=True).distinct()

    cidades = models.Cidade.objects.filter(pk__in=cidadesEmpresa)
    return render(request, 'agenda/login.html', {'form': form, 'cidades': cidades})


def logout_view(request):
    auth.logout(request)
    return redirect('agenda:login')

@login_required(login_url='agenda:login')
def home(request):
    if 'id_cidade' in request.session and request.session['id_cidade']:
        empresas = models.Empresa.objects.filter(gerente_id=3, cidade_id=request.session['id_cidade'])
    else:
        empresas = models.Empresa.objects.filter(gerente_id=3)
        
   

    return render(request, 'agenda/home.html',{'empresas': empresas})



def create_cliente(request):
    if request.method == 'POST':
        username = request.POST['username'] 
        email = request.POST['email']
        password = request.POST['password']
        confirmar_senha = request.POST['confirmar_senha']
        
        status = True
        usernameErros = []
        emailErros = []
        passwordErros = []
        
        if username == '':
            status = False
            usernameErros.append('Este campo é obrigatório.')
        
        if email == '':
            status = False
            emailErros.append('Este campo é obrigatório.')
            
        if password == '':
            status = False
            passwordErros.append('Este campo é obrigatório.')
            
        if password != confirmar_senha:
            status = False
            passwordErros.append('As senhas não conferem.')
            
        if models.User.objects.filter(email=email).exists():
            status = False
            emailErros.append('Este e-mail já está cadastrado.')
            
        
        if(status):
            user = models.User.objects.create_user(username=username, email=email, password=password, tipo='C')
            return redirect('agenda:home')
        
        return render(request, 'agenda/create-cliente.html', {
                'usernameErros': usernameErros, 'emailErros': emailErros, 'passwordErros': passwordErros,
                'username': username, 'email': email, 'password': password, 'confirmar_senha': confirmar_senha
                })
                    
    else:
        return render(request, 'agenda/create-cliente.html')
    
    
def cadastrarFuncionario(request):
    if request.method == 'POST':
        username = request.POST['nome'] 
        email = request.POST['email']
        password = request.POST['password']
        idEmpresa = request.POST.getlist('idEmpresa')
        idServico = request.POST.getlist('idServico')
        idDias = request.POST.getlist('idDia')
        horaInicial = request.POST['horaInicial']
        horaFinal = request.POST['horaFinal']
        foto = request.FILES['foto']  
       
        funcionario = models.User.objects.create_user(username=username, email=email, password=password, foto=foto, tipo='F')
        # Supondo que idEmpresa seja uma lista de IDs de empresas
        for empresa_id in idEmpresa:
            models.EmpresaFuncionario.objects.create(empresa_id=empresa_id, funcionario_id=funcionario.pk)

        # Supondo que idServico seja uma lista de IDs de serviços
        for servico_id in idServico:
            models.ServicoFuncionario.objects.create(servico_id=servico_id, funcionario_id=funcionario.pk)
            
        for dia_id in idDias:
            models.DiaSemanaFuncionario.objects.create(dia_id=dia_id, funcionario_id=funcionario.pk, horaInicial=horaInicial, horaFinal=horaFinal)
        
        return redirect('agenda:cadastrarFuncionario')
                    
    dias = models.Dia.objects.all()
    empresas = models.Empresa.objects.filter(gerente_id=request.user.pk, status=True)
    servicos = models.Servico.objects.filter(empresa_id__in=empresas, status=True)
    funcionarios = models.EmpresaFuncionario.objects.filter(empresa_id__in=empresas, funcionario__status=True)
    return render(request, 'agenda/cadastrar-funcionario.html', {
        'empresas': empresas,
        'dias': dias,
        'servicos': servicos,
        'funcionarios': funcionarios})

def updateFuncionario(request):
    if request.method == 'POST':
        username = request.POST['nome'] 
        email = request.POST['email']
        id_funcionario = request.POST['id_funcionario']
        idEmpresa = request.POST.getlist('idEmpresa')
        idServico = request.POST.getlist('idServico')
        idDias = request.POST.getlist('idDia')
        horaInicial = request.POST['horaInicial']
        horaFinal = request.POST['horaFinal']
        foto = request.FILES['foto']  
       
        funcionario, _ = models.User.objects.update_or_create(pk=id_funcionario, defaults= {'username':username, 'email':email, 'foto':foto})
        # Supondo que idEmpresa seja uma lista de IDs de empresas
        for empresa_id in idEmpresa:
            models.EmpresaFuncionario.objects.update_or_create(
                empresa_id=empresa_id, funcionario_id=funcionario.pk,
                defaults={'empresa_id':empresa_id, 'funcionario_id':funcionario.pk})

        # Supondo que idServico seja uma lista de IDs de serviços
        for servico_id in idServico:
            models.ServicoFuncionario.objects.update_or_create(
                servico_id=servico_id, funcionario_id=funcionario.pk,
                defaults={'servico_id':servico_id, 'funcionario_id':funcionario.pk})
            
        for dia_id in idDias:
            models.DiaSemanaFuncionario.objects.update_or_create(dia_id=dia_id, funcionario_id=funcionario.pk, horaInicial=horaInicial, horaFinal=horaFinal)
        
        return redirect('agenda:cadastrarFuncionario')

    idFuncionario = request.GET['id_funcionario'] 
    funcionario = models.User.objects.get(pk=idFuncionario, status=True)
    
    diasFun = models.DiaSemanaFuncionario.objects.filter(funcionario_id=funcionario.pk)
    diasFunHora = models.DiaSemanaFuncionario.objects.filter(funcionario_id=funcionario.pk).first()
    dias = models.Dia.objects.all().exclude(id__in=diasFun.values_list('dia_id', flat=True))
    
    empresasFun =  models.EmpresaFuncionario.objects.filter(funcionario_id=funcionario.pk)
    empresas = models.Empresa.objects.filter(gerente_id=request.user.pk, status=True).exclude(id__in=empresasFun.values_list('empresa_id', flat=True))
    
    servicosFun = models.ServicoFuncionario.objects.filter(funcionario_id=funcionario.pk)
    servicos = models.Servico.objects.filter(empresa_id__in=empresas, status=True).exclude(id__in=servicosFun.values_list('servico_id', flat=True))

    return render(request, 'agenda/update-funcionario.html',{
        'empresas': empresas,
        'empresasFun': empresasFun,
        'dias': dias,
        'diasFun': diasFun,
        'funcionario': funcionario,
        'diasFunHora': diasFunHora,
        'servicos': servicos,
        'servicosFun': servicosFun})
    
def deletarFuncionario(request):
    if request.method == 'POST':
        idFuncionario = request.POST['idFuncionario'] 
        models.User.objects.filter(pk=idFuncionario).update(status=False)
        
    return redirect('agenda:cadastrarFuncionario')

@login_required(login_url='agenda:login')
def perfil(request):
    
    if request.user.tipo == 'F':
        agendaHistorico = models.Agenda.objects.filter(funcionario=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='E')[:3]
    else:
        agendaHistorico = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='E')[:3]
        
    agendaMarcada = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='M')[:4]
    agendaProgramada = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='P')[:4]
    

    primeiro_dia_mes_atual = timezone.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    primeiro_dia_proximo_mes = (primeiro_dia_mes_atual + timedelta(days=32)).replace(day=1)
    servicoRealizadoFunc = models.Agenda.objects.filter(
        data_inicio__gte=primeiro_dia_mes_atual,
        data_inicio__lt=primeiro_dia_proximo_mes,
        status='E',
        servico__empresa__pk= request.session['id_empresa'])
    

agenda/templates/agenda/agendamento.html
{% extends 'global/base.html' %}
{% load static %}
{% load tz %}
{% block 'head' %}
<link href="{% static 'agenda/css/login.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Minha Agenda{% endblock 'titulo' %}

{% block 'conteudo' %}
{% include 'global/menu.html' %}
<section class="p-0 bg-secondary-subtle">

    <div class="container p-0 h-100 bg-white">
        <h1 class="text-center pt-2">Serviço Agendando</h1>
        <div class="m-3 d-flex justify-content-center">
            <form action="{% url 'agenda:agendamento' %}" method="GET">
                {% csrf_token %}
                <input type="date" id="data" name="data" value="{{ data }}" min="" required>
                <button type="submit" class="btn ms-3 btn-primary">Buscar</button>
            </form>
        </div>
        <div class="mt-3 pb-5 d-flex justify-content-center flex-wrap">
            {% for agenda in agendas %}
                <div class="card text-center m-auto mt-3"  style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ agenda.servico.nome }}</h5>
                        <p class="card-text">{{ agenda.servico.descricao }}</p>
                        <p class="card-text">Valor: {{ agenda.servico.valor }}</p>
                        <p class="card-text">Tempo: {{ agenda.servico.tempoServico }}</p>
                        <p class="card-text">Cliente: {{ agenda.cliente.username }}</p>
                        <p class="card-text">Horário: {{ agenda.data_inicio|timezone:"UTC"|time:"H:i" }}  ás {{ agenda.data_final|timezone:"UTC"|time:"H:i" }}</p>
                        <div class="d-flex justify-content-center"> 
                        <form class="pe-2" action="{% url 'agenda:cancelarAgendamento' %}" method="POST">
                            {% csrf_token %}
                            <div class="d-flex justify-content-end">
                                <input type="text" id="idAgenda" name="idAgenda" value="{{ agenda.pk }}" class="d-none">
                                <input type="text" id="path" name="path" value="{{ request.path }}" class="d-none">
                                <button type="submit" class="btn btn-danger">Cancelar</button>
                            </div>
                        </form>
                       
                        <form action="{% url 'agenda:agendamento' %}" method="POST">
                            {% csrf_token %}
                            <input class="visually-hidden" type="text" id="id_agenda" name="id_agenda" value="{{ agenda.pk }}" >
                            <button type="submit" class="btn btn-primary">Comfimar</button>
                        </form>
                    </div>
                    </div>
                </div>
            {% endfor %}    

        </div>
    </div>
</section>
<script>
    // Obter a data atual
    var dataAtual = new Date();
           // Adicionar 1 dia à data atual
    dataAtual.setDate(dataAtual.getDate());
    // Formatando a data atual como 'YYYY-MM-DD'
    var dataFormatada = dataAtual.toISOString().split('T')[0];

    // Definir o atributo 'min' com a data formatada
    document.getElementById('data').setAttribute('min', dataFormatada);
</script>
{% endblock 'conteudo' %}

agenda/templates/agenda/cadastrar-servico.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
<link href="{% static 'agenda/css/login.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Meu Serviço{% endblock 'titulo' %}

{% block 'conteudo' %}
{% include 'global/menu.html' %}
<section class="p-0 bg-secondary-subtle">
    <div class="container pb-3 h-100 bg-white">
        <h1 class="text-center pt-2">Cadastra Serviço</h1>
        <form action="{% url 'agenda:cadastrarServico' %}" method="POST" class="row g-3 w-50 m-auto p-3 shadow" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" name="nome" id="nome"  value="{{ servicoupdate.nome }}" placeholder="Nome"  required>
            </div>
            <div class="col-md-6">
                <label for="valor" class="form-label">Valor</label>
                <input type="text" class="form-control" id="valor" name="valor"  value="{{ servicoupdate.valor }}" placeholder="Valor" required>
            </div>
            <div class="col-6">
                <label for="tempoServico" class="form-label">Tempo Serviço</label>
                <input type="time" class="form-control" id="tempoServico" name="tempoServico"  value="{{ servicoupdate.tempoServico }}" placeholder="Tempo Serviço" required>
            </div>
            <div class="col-6">
                <label for="empresa" class="form-label">Unidade</label>
                <select class="form-select" name="idempresa" aria-label="Default select example">
                    {% if servicoupdate %}
                        <option selected value="{{ servicoupdate.empresa.pk }}">{{ servicoupdate.empresa.nome }}</option>
                    {% else %}
                        <option disabled selected>Selecione um Unidade</option>
                    {% endif %}

                    
                    {% if empresas %}
                        {% for empresa in empresas %}
                             {% if servicoupdate.empresa.pk != empresa.pk %}
                                <option value="{{ empresa.pk }}">{{ empresa.nome }}</option>
                            {% endif %}
                        {% endfor %}     
                    {% endif %}
                </select>
            </div>
            <div class="col-md-12">
                <label for="descricao" class="form-label">Descrição</label>
                <textarea class="form-control" id="descricao" name="descricao" rows="5">{{ servicoupdate.descricao }}</textarea>
            </div>
            <div class="col-md-12">
                <div class="input-group mb-3">
                    <label class="input-group-text" for="foto">Foto</label>
                    <input type="file" class="form-control" name="foto" id="foto" required>
            </div>
            <div class="col-12 d-flex justify-content-center">
                <input type="text" class="d-none" id="id_servicoupdate" name="id_servicoupdate" value="{{ servicoupdate.pk }}">
                <button type="submit" class="btn btn-primary">Cadastra</button>
            </div>
        </form>
    </div>
    <div class="container pt-4 h-100 bg-white">
        <h1 class="ms-3">Meu Serviço</h1>
        <div class="d-flex justify-content-center flex-wrap">
            {% if servicos %}
                {% for servico in servicos %}
                    <div class="card m-2 w-60" style="width: 50%;">
                        <div class="row g-0">
                            <div class="col-md-4 d-flex justify-content-center">
                                {% if servico.foto.url %}
                                <img src="{{ servico.foto.url }}" class="img-fluid rounded-start" alt="...">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ servico.nome }}</h5>
                                    <p class="card-text">{{ servico.descricao }}</p>
                                    <p class="card-text">Valor: R${{ servico.valor }}</p>
                                    <p class="card-text">Tempo Serviço: {{ servico.tempoServico }}h</p>
                                    <p class="card-text"><small class="text-body-secondary">{{ servico.empresa.nome }}</small></p>
                                    <div class="d-flex justify-content-end"> 
                                    <form class="pe-2" action="{% url 'agenda:deletarServico' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="col-12 d-flex justify-content-end">
                                            <input type="text" id="idServico" name="idServico" value="{{ servico.pk }}" class="d-none">
                                            <button type="submit" class="btn btn-danger">Deletar</button>
                                        </div>
                                    </form>
                                    <form action="{% url 'agenda:cadastrarServico' %}" method="GET">
                                        {% csrf_token %}
                                        <div class="col-12 d-flex justify-content-end">
                                            <input type="text" id="id_servico" name="id_servico" value="{{ servico.pk }}" class="d-none">
                                            <button type="submit" class="btn btn-primary">Editar</button>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}     
            {% endif %}
        </div>
    </div>
</section>
{% endblock 'conteudo' %}

agenda/templates/agenda/empresa.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
<link href="{% static 'agenda/css/login.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Minha Unidade{% endblock 'titulo' %}

{% block 'conteudo' %}
{% include 'global/menu.html' %}
<section class="p-0 bg-secondary-subtle">
    <div class="container pb-3 h-100 bg-white">
        <h1 class="text-center pt-2">Cadastra Unidade</h1>
        <form action="{% url 'agenda:empresa' %}" method="POST" class="row g-3 w-50 m-auto p-3 shadow" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="nome" class="form-label">Nome</label>
                <input type="text" class="form-control" name="nome" id="nome" placeholder="Nome" value="{{ empresaupdate.nome }}" required>
            </div>
            <div class="col-md-6">
                <label for="cep" class="form-label">CEP</label>
                <input type="text" class="form-control" id="cep" name="cep" placeholder="CEP" value="{{ empresaupdate.cep }}" required>
            </div>
            <div class="col-md-12">
                <label for="logradouro" class="form-label">Logradouro</label>
                <input type="text" class="form-control" id="logradouro" name="logradouro" placeholder="Logradouro" value="{{ empresaupdate.logradouro }}" required>
            </div>
            <div class="col-md-12">
                <label for="idCidade" class="form-label">Cidade</label>
                <input list="listaCidades" id="idCidade" name="idCidade" value="{{ empresaupdate.cidade.nome  }}" />
                    <datalist id="listaCidades">
                    {% if cidades %}
                        {% for cidade in cidades %}
                            <option value="{{ cidade.nome }}"></option>
                        {% endfor %}     
                    {% endif %}
                </datalist>
            </div>
            <div class="col-6">
                <label for="numero" class="form-label">Numero</label>
                <input type="text" class="form-control" id="numero" name="numero" placeholder="Numero" value="{{ empresaupdate.numero }}" required>
            </div>
            <div class="col-6">
                <label for="complemento" class="form-label">Complemento</label>
                <input type="text" class="form-control" id="complemento" name="complemento" value="{{ empresaupdate.complemento }}" placeholder="Complemento">
            </div>
            <div class="col-md-12">
                <label for="descricao" class="form-label">Descrição</label>
                <textarea class="form-control" id="descricao" name="descricao" rows="5">{{ empresaupdate.descricao }}</textarea>
            </div>
            <div class="col-md-12">
                <div class="input-group mb-3">
                    <label class="input-group-text" for="foto">Foto</label>
                    <input type="file" class="form-control" name="foto" id="foto" required>
                </div>
            </div>

            <div class="col-12 d-flex justify-content-center">
                <input type="text" class="d-none" id="id_empresaupdate" name="id_empresaupdate" value="{{ empresaupdate.pk }}">
                <button type="submit" class="btn btn-primary">Cadastra</button>
            </div>
        </form>
    </div>
    <div class="container pt-4 h-100 bg-white">
        <h1 class="ms-3">Minhas Unidade</h1>
        <div class="d-flex justify-content-center flex-wrap">
            {% if empresas %}
                {% for empresa in empresas %}
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-md-4">
                                {% if empresa.foto %}
                                <img src="{{ empresa.foto.url }}" class="img-fluid rounded-start" alt="...">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ empresa.nome }}</h5>
                                    <p class="card-text">{{ empresa.descricao }}</p>
                                    <p class="card-text">Logradouro: {{ empresa.logradouro }}</p>
                                    <p class="card-text">CEP: {{ empresa.cep }}</p>
                                    <p class="card-text">Número: {{ empresa.numero }}</p>
                                    <div class="d-flex justify-content-end"> 
                                    <form class="pe-2" action="{% url 'agenda:deletarEmpresa' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="col-12 d-flex justify-content-end">
                                            <input type="text" id="idempresa" name="idempresa" value="{{ empresa.pk }}" class="d-none">
                                            <button type="submit" class="btn btn-danger">Deletar</button>
                                        </div>
                                    </form>
                                    <form action="{% url 'agenda:empresa' %}" method="GET">
                                        {% csrf_token %}
                                        <div class="col-12 d-flex justify-content-end">
                                            <input type="text" id="id_empresa" name="id_empresa" value="{{ empresa.pk }}" class="d-none">
                                            <button type="submit" class="btn btn-primary">Editar</button>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}     
            {% endif %}
        </div>
    </div>
</section>
{% endblock 'conteudo' %}

agenda/templates/agenda/index.html
{% extends 'global/base.html' %}
{% load static %}
{% block 'head' %}
    <link href="{% static 'agenda/css/style.css' %}" rel="stylesheet">
{% endblock 'head' %}

{% block 'titulo' %}Agenda Serviço{% endblock 'titulo' %}

{% block 'conteudo' %}

<h1>Agora vai!!</h1>
  
{% endblock 'conteudo' %}

agenda/templates/agenda/lista-empresas.html
<label>Empresa</label>
<select class="form-control form-control-lg shadow p-4 mb-2 bg-white rounded" id="codigo" name="codigo" required>
    <option disabled selected>Selecione a Empresa</option>
    {% for empresa in empresas %}
        <option value="{{ empresa.pk }}">{{ empresa.nome }}</option>
    {% endfor %}  
</select>