agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('login/', views.login_in, name='login'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/create-cliente', views.create_cliente, name='create_cliente'),
    path('perfil/', views.perfil, name='perfil'),
    path('empresa/', views.empresa, name='empresa'),
    path('servico/', views.servico, name='servico'),
    path('agenda/', views.agenda, name='agenda'),
    path('agendamento/', views.agendamento, name='agendamento'),
    path('gerarAgendamento/', views.gerarAgendamento, name='gerarAgendamento'),
    path('gerar-agendamento-programado/', views.gerarAgendamentoProgramado, name='gerarAgendamentoProgramado'),
    path('cancelar-agendamento/', views.cancelarAgendamento, name='cancelarAgendamento'),
    path('cadastrar-servico/', views.cadastrarServico, name='cadastrarServico'),
    path('cadastrar-funcionario/', views.cadastrarFuncionario, name='cadastrarFuncionario'),
    path('update-funcionario/', views.updateFuncionario, name='updateFuncionario'),
    path('deletar-servico/', views.deletarServico, name='deletarServico'),
    path('deletar-empresa/', views.deletarEmpresa, name='deletarEmpresa'),
    path('deletar-funcionario/', views.deletarFuncionario, name='deletarFuncionario'),
]

servicoAgenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('agenda.urls'), name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):   
    TIPO_ADM_CHOICES = (('G', 'Gerente'), ('F', 'Funcionario'), ('C', 'Cliente'))
    
    id = models.AutoField(primary_key=True)
    celular = models.CharField(max_length=20, blank=True, null=True)
    username = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(unique=True)
    tipo = models.CharField(max_length=1, choices=TIPO_ADM_CHOICES)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    status = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']
    
class Dia(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=30)

class DiaSemanaFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    horaInicial = models.TimeField()
    horaFinal = models.TimeField()
    dia = models.ForeignKey(Dia, on_delete=models.SET_NULL, blank=True, null=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    
class Cidade(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)

class Empresa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    logradouro = models.CharField(max_length=200, blank=True, null=True)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    descricao = models.CharField(max_length=200, blank=True, null=True)
    cep = models.CharField(max_length=200, blank=True, null=True)
    numero = models.CharField(max_length=200, blank=True, null=True)
    complemento = models.CharField(max_length=200, blank=True, null=True)
    status = models.BooleanField(default=True)
    gerente = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.SET_NULL, blank=True, null=True)
            
class Servico(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    descricao = models.CharField(max_length=200, blank=True, null=True)
    valor = models.FloatField()
    tempoServico = models.TimeField()
    intervalo = models.TimeField(blank=True, null=True)
    status = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='imagens/', null=True, blank=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.SET_NULL, blank=True, null=True)
    
class ServicoFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    servico = models.ForeignKey(Servico, on_delete=models.SET_NULL, blank=True, null=True)
    
        
class Agenda(models.Model):
    STATUS = (('M', 'Marcado'),('P', 'Programado'), ('E', 'Executado'), ('C', 'Cancelado'))
    id = models.AutoField(primary_key=True)
    create_data = models.DateTimeField(auto_now_add=True)
    data_inicio = models.DateTimeField()
    data_final = models.DateTimeField()
    status = models.CharField(max_length=1, choices=STATUS)
    servico = models.ForeignKey(Servico, on_delete=models.SET_NULL, blank=True, null=True)
    cliente = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='agendas_cliente')
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='agendas_funcionario')
    
class EmpresaFuncionario(models.Model):
    id = models.AutoField(primary_key=True)
    funcionario = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    empresa = models.ForeignKey(Empresa, on_delete=models.SET_NULL, blank=True, null=True)
    

agenda/views.py
from calendar import c
from cgi import print_arguments
from turtle import mode
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from agenda.util import encontrar_menor_maior_hora, dividir_horarios, filtrar_horarios_nao_ocupados
from agenda import models
from django.urls import resolve
from django.utils import timezone
from django.core.mail import send_mail



def index(request):
    return render(request, 'agenda/index.html')

def login_in(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)
                request.session['id_empresa'] = 11
                request.session['statusAgenda'] = 'M'
                if 'idCidade' in request.POST and request.POST['idCidade']:
                    request.session['id_cidade'] = request.POST['idCidade'] 

                if user.tipo == 'C':
                    return redirect('agenda:home')
                
                return redirect('agenda:perfil')
    else:
        form = AuthenticationForm()
        
    cidadesEmpresa = models.Empresa.objects.filter(gerente_id=3).values_list('cidade', flat=True).distinct()

    cidades = models.Cidade.objects.filter(pk__in=cidadesEmpresa)
    return render(request, 'agenda/login.html', {'form': form, 'cidades': cidades})


def logout_view(request):
    auth.logout(request)
    return redirect('agenda:login')

@login_required(login_url='agenda:login')
def home(request):
    if 'id_cidade' in request.session and request.session['id_cidade']:
        empresas = models.Empresa.objects.filter(gerente_id=3, cidade_id=request.session['id_cidade'])
    else:
        empresas = models.Empresa.objects.filter(gerente_id=3)
        
   

    return render(request, 'agenda/home.html',{'empresas': empresas})



def create_cliente(request):
    if request.method == 'POST':
        username = request.POST['username'] 
        email = request.POST['email']
        password = request.POST['password']
        confirmar_senha = request.POST['confirmar_senha']
        
        status = True
        usernameErros = []
        emailErros = []
        passwordErros = []
        
        if username == '':
            status = False
            usernameErros.append('Este campo é obrigatório.')
        
        if email == '':
            status = False
            emailErros.append('Este campo é obrigatório.')
            
        if password == '':
            status = False
            passwordErros.append('Este campo é obrigatório.')
            
        if password != confirmar_senha:
            status = False
            passwordErros.append('As senhas não conferem.')
            
        if models.User.objects.filter(email=email).exists():
            status = False
            emailErros.append('Este e-mail já está cadastrado.')
            
        
        if(status):
            user = models.User.objects.create_user(username=username, email=email, password=password, tipo='C')
            return redirect('agenda:home')
        
        return render(request, 'agenda/create-cliente.html', {
                'usernameErros': usernameErros, 'emailErros': emailErros, 'passwordErros': passwordErros,
                'username': username, 'email': email, 'password': password, 'confirmar_senha': confirmar_senha
                })
                    
    else:
        return render(request, 'agenda/create-cliente.html')
    
    
def cadastrarFuncionario(request):
    if request.method == 'POST':
        username = request.POST['nome'] 
        email = request.POST['email']
        password = request.POST['password']
        idEmpresa = request.POST.getlist('idEmpresa')
        idServico = request.POST.getlist('idServico')
        idDias = request.POST.getlist('idDia')
        horaInicial = request.POST['horaInicial']
        horaFinal = request.POST['horaFinal']
        foto = request.FILES['foto']  
       
        funcionario = models.User.objects.create_user(username=username, email=email, password=password, foto=foto, tipo='F')
        # Supondo que idEmpresa seja uma lista de IDs de empresas
        for empresa_id in idEmpresa:
            models.EmpresaFuncionario.objects.create(empresa_id=empresa_id, funcionario_id=funcionario.pk)

        # Supondo que idServico seja uma lista de IDs de serviços
        for servico_id in idServico:
            models.ServicoFuncionario.objects.create(servico_id=servico_id, funcionario_id=funcionario.pk)
            
        for dia_id in idDias:
            models.DiaSemanaFuncionario.objects.create(dia_id=dia_id, funcionario_id=funcionario.pk, horaInicial=horaInicial, horaFinal=horaFinal)
        
        return redirect('agenda:cadastrarFuncionario')
                    
    dias = models.Dia.objects.all()
    empresas = models.Empresa.objects.filter(gerente_id=request.user.pk, status=True)
    servicos = models.Servico.objects.filter(empresa_id__in=empresas, status=True)
    funcionarios = models.EmpresaFuncionario.objects.filter(empresa_id__in=empresas, funcionario__status=True)
    return render(request, 'agenda/cadastrar-funcionario.html', {
        'empresas': empresas,
        'dias': dias,
        'servicos': servicos,
        'funcionarios': funcionarios})

def updateFuncionario(request):
    if request.method == 'POST':
        username = request.POST['nome'] 
        email = request.POST['email']
        id_funcionario = request.POST['id_funcionario']
        idEmpresa = request.POST.getlist('idEmpresa')
        idServico = request.POST.getlist('idServico')
        idDias = request.POST.getlist('idDia')
        horaInicial = request.POST['horaInicial']
        horaFinal = request.POST['horaFinal']
        foto = request.FILES['foto']  
       
        funcionario, _ = models.User.objects.update_or_create(pk=id_funcionario, defaults= {'username':username, 'email':email, 'foto':foto})
        # Supondo que idEmpresa seja uma lista de IDs de empresas
        for empresa_id in idEmpresa:
            models.EmpresaFuncionario.objects.update_or_create(
                empresa_id=empresa_id, funcionario_id=funcionario.pk,
                defaults={'empresa_id':empresa_id, 'funcionario_id':funcionario.pk})

        # Supondo que idServico seja uma lista de IDs de serviços
        for servico_id in idServico:
            models.ServicoFuncionario.objects.update_or_create(
                servico_id=servico_id, funcionario_id=funcionario.pk,
                defaults={'servico_id':servico_id, 'funcionario_id':funcionario.pk})
            
        for dia_id in idDias:
            models.DiaSemanaFuncionario.objects.update_or_create(dia_id=dia_id, funcionario_id=funcionario.pk, horaInicial=horaInicial, horaFinal=horaFinal)
        
        return redirect('agenda:cadastrarFuncionario')

    idFuncionario = request.GET['id_funcionario'] 
    funcionario = models.User.objects.get(pk=idFuncionario, status=True)
    
    diasFun = models.DiaSemanaFuncionario.objects.filter(funcionario_id=funcionario.pk)
    diasFunHora = models.DiaSemanaFuncionario.objects.filter(funcionario_id=funcionario.pk).first()
    dias = models.Dia.objects.all().exclude(id__in=diasFun.values_list('dia_id', flat=True))
    
    empresasFun =  models.EmpresaFuncionario.objects.filter(funcionario_id=funcionario.pk)
    empresas = models.Empresa.objects.filter(gerente_id=request.user.pk, status=True).exclude(id__in=empresasFun.values_list('empresa_id', flat=True))
    
    servicosFun = models.ServicoFuncionario.objects.filter(funcionario_id=funcionario.pk)
    servicos = models.Servico.objects.filter(empresa_id__in=empresas, status=True).exclude(id__in=servicosFun.values_list('servico_id', flat=True))

    return render(request, 'agenda/update-funcionario.html',{
        'empresas': empresas,
        'empresasFun': empresasFun,
        'dias': dias,
        'diasFun': diasFun,
        'funcionario': funcionario,
        'diasFunHora': diasFunHora,
        'servicos': servicos,
        'servicosFun': servicosFun})
    
def deletarFuncionario(request):
    if request.method == 'POST':
        idFuncionario = request.POST['idFuncionario'] 
        models.User.objects.filter(pk=idFuncionario).update(status=False)
        
    return redirect('agenda:cadastrarFuncionario')

@login_required(login_url='agenda:login')
def perfil(request):
    
    if request.user.tipo == 'F':
        agendaHistorico = models.Agenda.objects.filter(funcionario=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='E')[:3]
    else:
        agendaHistorico = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='E')[:3]
        
    agendaMarcada = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='M')[:4]
    agendaProgramada = models.Agenda.objects.filter(cliente_id=request.user.pk, servico__empresa__pk= request.session['id_empresa'], status='P')[:4]
    

    primeiro_dia_mes_atual = timezone.now().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    primeiro_dia_proximo_mes = (primeiro_dia_mes_atual + timedelta(days=32)).replace(day=1)
    servicoRealizadoFunc = models.Agenda.objects.filter(
        data_inicio__gte=primeiro_dia_mes_atual,
        data_inicio__lt=primeiro_dia_proximo_mes,
        status='E',
        servico__empresa__pk= request.session['id_empresa'])
    

agenda/templates/agenda/sencao/perfil-cliente-historico.html
{% load tz %}
<div class="container h-100 d-flex bg-white">
    <div class="w-50 p-5">
        <h2>Serviço Marcado</h2>
        {% if agendaMarcada %}
            {% for agenda in agendaMarcada %}
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex justify-content-center">
                            <img src="{{ agenda.servico.foto.url }}" class="img-fluid" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ agenda.servico.nome }}</h5>
                                <p class="card-text">{{ agenda.servico.descricao }}</p>
                                <p class="card-text"><small class="text-body-secondary"> {{ agenda.funcionario.username}} </small></p>
                                <p class="card-text"><small class="text-body-secondary">{{ agenda.data_inicio|date:"l, d F Y"  }} ás {{ agenda.data_inicio|timezone:"UTC"|time:"H:i" }} 
                                    as {{ agenda.data_final|timezone:"UTC"|time:"H:i" }}</small>
                                </p>
                                <form class="pe-2" action="{% url 'agenda:cancelarAgendamento' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="d-flex justify-content-end">
                                        <input type="text" id="idAgenda" name="idAgenda" value="{{ agenda.pk }}" class="d-none">
                                        <input type="text" id="path" name="path" value="{{ request.path }}" class="d-none">
                                        <button type="submit" class="btn btn-danger">Cancelar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}     
        {% endif %}
    </div>

    <div class="w-50 p-5">
        <div class="d-flex justify-content-between">
        <h2>Solicitação de Encaixe</h2>
        <form action="{% url 'agenda:gerarAgendamentoProgramado' %}" method="GET">
            {% csrf_token %}
                <button type="submit" class="btn btn-primary">Solicitar</button>        
        </form>
    </div>
        {% if agendaProgramada %}
        {% for agenda in agendaProgramada %}
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4 d-flex justify-content-center">
                        <img src="{{ agenda.servico.foto.url }}" class="img-fluid" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ agenda.servico.nome }}</h5>
                            <p class="card-text">{{ agenda.servico.descricao }}</p>
                            <p class="card-text"><small class="text-body-secondary"> {{ agenda.funcionario.username}} </small></p>
                            <p class="card-text"><small class="text-body-secondary">{{ agenda.data_inicio|date:"l, d F Y" }} ás {{ agenda.data_inicio|timezone:"UTC"|time:"H:i" }} 
                                as {{ agenda.data_final|timezone:"UTC"|time:"H:i" }}</small>
                            </p>
                            <form class="pe-2" action="{% url 'agenda:cancelarAgendamento' %}" method="POST">
                                {% csrf_token %}
                                <div class="d-flex justify-content-end">
                                    <input type="text" id="idAgenda" name="idAgenda" value="{{ agenda.pk }}" class="d-none">
                                    <input type="text" id="path" name="path" value="{{ request.path }}" class="d-none">
                                    <button type="submit" class="btn btn-danger">Cancelar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}     
    {% endif %}
    </div>
</div>